name: Libunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  real-tests:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: make -C real_tests re
    - name: Test
      run: make -C real_tests test

